name: Build and Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Deploy via rsync
      - name: Rsync deploy to server
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avz --delete
          path: .
          remote_path: /home/inzynierka/www/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_port: ${{ secrets.SERVER_PORT }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
          exclude: |
            .env
            storage/
            public/favicon.ico
            node_modules/
            vendor/

      - name: SSH run (Laravel build)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/inzynierka/www

            composer install --no-dev --optimize-autoloader
  
            php artisan migrate --force
            php artisan scribe:generate
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:clear